#!/system/bin/sh

echo " Disabling GMS GIOS "
sleep 0.5
echo " and enabling Auto Switch display mode to 60hz when idle "
sleep 1 

echo "█░░░░"
sleep 0.5 
echo "██░░░"
sleep 1
echo "███░░"
sleep 1 
echo "████░"
sleep 1 
echo "█████ 100%"

  pm disable com.google.android.gms/.chimera.GmsIntentOperationService

echo " ➤Switch display mode to 60hz when idle"
sleep 0.5
  /sys/devices/platform/soc/soc:qcom,dsi-display-primary/idle_mode "@60"
sleep 2 
echo " Made by @unrthdox95 "
sleep 1
echo " exiting now✅ "
sleep 1

am force-stop com.termux



